name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: docker://python:3.9.4-slim-buster

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Unit test
      run: |
        pytest -vvv
